#
# man/Makefile	man/ Makefile for the net-tools Package
#
# NET-TOOLS	A collection of programs that form the base set of the
#		NET-3 Networking Distribution for the LINUX operating
#		system.
#
# Version:	Makefile 0.01 (1996-03-22)
#
# Author:	Bernd Eckenfels <net-tools@lina.inka.de>
#		Copyright 1995-1996 Bernd Eckebnfels, Germany
#
#960322	{0.01}	Bernd Eckenfels:	creation to make main Makefile cleaner
#
#	This program is free software; you can redistribute it
#	and/or  modify it under  the terms of  the GNU General
#	Public  License as  published  by  the  Free  Software
#	Foundation;  either  version 2 of the License, or  (at
#	your option) any later version.
#


all:

clean:
		rm -f DEADJOE *~ *.orig
		rm -f */DEADJOE */*~ */*.orig

clobber:	clean

# End of man/Makefile.
