name: Compile net-tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install-dev
      run: sudo apt-get install libbluetooth-dev libselinux1-dev gettext

    - name: configure
      run: yes "" | make config

    - name: compile
      run: make distcheck
